name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: mayhrem
          POSTGRES_PASSWORD: task-1920892
          POSTGRES_DB: taskdb
        options: >-
          --health-cmd "pg_isready -U mayhrem"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build backend
        run: |
          cd task-backend
          mvn clean package

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: |
          cd task-frontend
          npm install

      - name: Build frontend
        run: |
          cd task-frontend
          npm run build

      - name: Run tests
        run: |
          cd task-backend
          mvn test