name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build backend
        working-directory: ./backend
        run: mvn clean install

      - name: Build frontend
        working-directory: ./frontend
        run: npm install && npm run build

      - name: Build Docker image
        run: docker build -t devops-crud-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to cloud
        run: |
          echo "Deploying to cloud environment..."
          # Add your deployment commands here (e.g., using Terraform or cloud CLI)